version: '3.5'

services:

    appserver:
        container_name: appserver
        build:
            context: ./appserver
            dockerfile: Dockerfile.prod
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=pizza
            - FLASK_APP_CONFIG=Production
            - FLASK_DEBUG=1
            - POSTGRES_HOST=database
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PORT=5432
