version: '3.5'

services:
    database:
        container_name: database
        image: postgres:11
        env_file:
            - ./prod.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    appserver:
        container_name: appserver
        command: ['bin/wait-for-postgres.sh', 'bin/startup.sh']
        build:
            context: ./appserver
            dockerfile: Dockerfile.prod
        ports:
            - 5000:5000
        env_file:
            - ./prod.env

    nginx:
        build: ./proxy
        ports:
            - 80:80

volumes:
    postgres_data: