version: '3.5'

services:
    database:
        container_name: database
        image: postgres:11
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        networks:
            - backend

    appserver:
        container_name: appserver
        command: ['bin/wait-for-postgres.sh', 'bin/startup.sh']
        build: ./appserver
        ports:
            - 5000:5000
        environment:
            - FLASK_APP=pizza
            - FLASK_APP_CONFIG=Development
            - FLASK_DEBUG=1
            - POSTGRES_HOST=database
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PORT=5432
        volumes:
            - ./appserver:/home/pizza
        networks:
            - backend

networks:
    backend: