version: '3.8'

services:
    appserver:
        container_name: appserver
        command: []
        environment:
            - FLASK_APP=pizza
            - FLASK_APP_CONFIG=Production
            - FLASK_ENV=production
            - POSTGRES_HOST=database
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=prodpassword
            - REDIS_SSL=False