version: '3.5'

services:
    database:
        container_name: database
        image: postgres:11
        env_file:
            - ./prod.env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    appserver:
        container_name: appserver
        image: davidbour/appserver
        ports:
            - 5000:5000
        env_file:
            - ./prod.env
        depends_on:
            - database

    nginx:
        container_name: nginx
        image: davidbour/nginx
        ports:
            - 80:80
        depends_on:
            - appserver

volumes:
    postgres_data: