version: "3.7"

services:

  neo4jproxy:
    container_name: neo4jproxy
    build:
      context: ./neo4jproxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 7687:7687
      - 8000:8000
    networks:
      - n4j
      - backend

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      # - ./neo4j/conf:/var/lib/neo4j/conf
    environment:
      - NEO4J_AUTH=neo4j/test
    expose:
      - 7474
      - 7687
    # ports:
    #   - 7474:7474
    #   - 7687:7687
    networks:
      - n4j
      # - backend

networks:
  n4j: