version: '3.5'

services:
    database:
        container_name: database
        image: postgres:11
        env_file:
            - ./prod.env
        expose:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    appserver:
        container_name: appserver
        build:
            context: ./appserver
            dockerfile: Dockerfile.prod
        expose:
            - "5000"
        env_file:
            - ./prod.env
        depends_on:
            - database

    nginx:
        container_name: nginx
        build:
            context: ./proxy
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - appserver

volumes:
    postgres_data: