"""empty message

Revision ID: faf0c36e651e
Revises: 7d8ee3de2f30
Create Date: 2020-05-02 16:28:44.554025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf0c36e651e'
down_revision = '7d8ee3de2f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'account', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'email')
    # ### end Alembic commands ###
