# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Docker Images

on:
  push:
    branches:
      - 'releases/**'

jobs:
  build:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Appserver & Push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: pizza.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: appserver
          image_tag: ${{ github.sha }},latest
          context: ./appserver
          dockerfile: ./Dockerfile
        
      - name: Build Client and Nginx
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: pizza.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: webserver
          image_tag: ${{ github.sha }},latest
          context: ./client
          dockerfile: ./Dockerfile
