name: Continuous Delivery

on: push

env:
    POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
    POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:
    build:
        name: Continuous Delivery
        runs-on: ubuntu-latest
        steps:
            - name: Try SSH
              uses: appleboy/ssh-action@master
              with:
                host: 165.227.26.118
                username: deployer
                password: ${{ secrets.DO_SSH_KEY_PASSWORD }}
                key: ${{ secrets.DO_SSH_KEY }}
                port: 22
                script: whoami

