name: Continuous Delivery - Digital Ocean

on: push

env:
    POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
    POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:
    build:
        name: Continuous Delivery
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Build Appserver & Push
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: davidbour/appserver
                tags: ${{ github.sha }}
                path: ./appserver
                dockerfile: ./appserver/Dockerfile.prod

            - name: Build Nginx & Push
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: davidbour/nginx
                tags: ${{ github.sha }}
                path: ./proxy
                dockerfile: ./proxy/Dockerfile

            - name: Build secrets
              run: |-
                echo "POSTGRES_HOST=$POSTGRES_HOST" >> prod.env
                echo "POSTGRES_PORT=$POSTGRES_PORT" >> prod.env
                echo "POSTGRES_USER=$POSTGRES_USER" >> prod.env
                echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> prod.env
                echo "POSTGRES_DB=$POSTGRES_DB" >> prod.env
                echo "FLASK_APP=pizza" >> prod.env
                echo "FLASK_APP_CONFIG=Production" >> prod.env
                echo "FLASK_ENV=production" >> prod.env

            - name: SCP docker-compose.prod.yml
              uses: appleboy/scp-action@master
              with:
                host: 165.227.26.118
                username: deployer
                passphrase: ${{ secrets.DO_SSH_KEY_PASSWORD }}
                key: ${{ secrets.DO_SSH_KEY }}
                port: 22
                source: "docker-compose.prod.yml"
                target: "/home/deployer/"

            - name: SCP secrets
              uses: appleboy/scp-action@master
              with:
                host: 165.227.26.118
                username: deployer
                passphrase: ${{ secrets.DO_SSH_KEY_PASSWORD }}
                key: ${{ secrets.DO_SSH_KEY }}
                port: 22
                source: "prod.env"
                target: "/home/deployer/"

            - name: Try SSH
              uses: appleboy/ssh-action@master
              with:
                host: 165.227.26.118
                username: deployer
                passphrase: ${{ secrets.DO_SSH_KEY_PASSWORD }}
                key: ${{ secrets.DO_SSH_KEY }}
                port: 22
                script: |
                    docker-compose -f docker-compose.prod.yml pull
                    docker-compose -f docker-compose.prod.yml up -d
                    docker system prune -f
