name: Application Test Suite

on: push

jobs:
    setup-test:
        name: Build Application Test Suite
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup build
              run: |
                docker-compose up --build -d
                docker-compose exec -T appserver bin/wait-for-postgres.sh

            - name: Testing
              run: |
                docker-compose exec -T appserver pytest
